#+TITLE: Equilibrium Structure
#+AUTHOR: Gun Woo Park

* Preface
This studies are related with the equilibrium structure for shear thickening solution. For developing the simulation, to know equilibrium structure is of importance. Hence, here is studies about equilibrium structure with various observables.

* Number of chains per beads and its equilibrium functionality (or coordination number)
The results from different condition shows that there are different aggregation patterns in terms of number of chains per beads. , which will test future. 
** Effects of increasing number of associations

* TODO The effects of number of allowance is NOT tested yet
* TEMPORAL equations
integration of RDF over relative distance vector
\begin{align}
\lim_{r\to\infty}\int g(\mathbf{r})d\mathbf{r} &= V \\
\Rightarrow &2\pi\rho \lim_{R\to\infty}\int_0^{R} rg(r)\,dr = Np
\end{align}
Coordination number
\begin{equation}
CN(r) = 2\pi\rho\int_0^r \tilde{r}g(\tilde{r})\,d\tilde{r}
\end{equation}
Noramalized coordination number
\begin{equation}
RCN(r) = \frac{CN(r)}{\rho \pi r^2}
\end{equation}
