
#+TITLE: Stochastic Simulation for Physical Network System
#+AUTHOR: Gun Woo Park

* Time Evolution for Positions of Micelle
The position of micelles are updated based on Langevin dynamics, which in consequence, have following form:
\begin{equation}
\frac{\partial \mathbf{r}_k}{\partial t} = \frac{1}{\zeta}\left(\sum_{i\in\mathscr{C}_k} \mathbf{F}^{(c)}(\mathbf{r}_i, \mathbf{r}_k) + \sum_i \mathbf{F}^{(r)}(\mathbf{r}_i, \mathbf{r}_k) + \mathbf{F}^{(s)}(\mathbf{r}_k)\right),
\end{equation}
where $\mathbf{F}^{(c)}$ is connection information and $\mathscr{C}_k$ is the chains attached to k-th particle, $\mathbf{F}^{(r)}$ is repulsive potential, and $\mathbf{F}^{(s)}$ and Brownian motion. The forces are given by
\begin{align}
\mathbf{F}^{(c)}(\mathbf{r}_i, \mathbf{r}_k) &= k_BTN_D\frac{\mathbf{r}_{ik}}{R_c^2} \\
\mathbf{F}^{(r)}(\mathbf{r}_i, \mathbf{r}_k) &= -C\frac{k_BT}{R_0}\left(1 - \frac{r_{ik}^2}{R_0^2}\right)\hat{\mathbf{r}}_{ik} \quad\textrm{when $r_{ik} < R_0$}.
\end{align}
With Euler integrator, we have
\begin{equation}
\mathbf{r}_k(t + \delta t') = \mathbf{r}_k(t) + \frac{k_BT}{\zeta}\delta t'\left[\sum_{i\in \mathscr{C}_k}N_D\frac{\mathbf{r}_{ik}}{R_c^2} - \sum_{i=1}^{N_p} \frac{C}{R_0}\left(1 - \frac{r_{ik}^2}{R_0^2}\right)\hat{\mathbf{r}}_{ik}\right] + \sqrt{\frac{2 k_BT \delta t'}{\zeta}}\tilde{\mathbf{R}},
\end{equation}
where $\tilde{\mathbf{R}}\sim \mathscr{N}(0, 1)$ that is normal distribution with average 0 and variance 1.
Since the fastest time scale for this system is given by
\begin{equation}
\tau_B = \frac{R_0^2\zeta}{k_BTC},
\end{equation}
we have non-dimensional form for evolution equation:
\begin{equation}
\tilde{\mathbf{r}}_k(\tilde{t}' + \delta \tilde{t}') = \tilde{\mathbf{r}}_k(\tilde{t}') + \frac{1}{C}\delta\tilde{t}'\sum_{i\in\mathscr{C}_k} N_D\alpha^2\tilde{\mathbf{r}}_{ik} + \delta\tilde{t}'  \sum_{i} (\tilde{r}_{ik}^2 - 1)\hat{\mathbf{r}_{ik}} + \sqrt{\frac{2}{C}}\sqrt{\delta \tilde{t}'}\tilde{\mathbf{R}},
\end{equation}
where $\alpha = R_0/R_c$ and prime is used since the characteristic time for the system is given by dissociation time, $\tau_D$. We can re-map to the non-dimensional form based on Brownian time to dissociation time, we have
\begin{equation}
\tilde{\mathbf{r}_k}\left(\tilde{t} + \left(\frac{\tau_B}{\tau_D}\delta \tilde{t}\right)\right) = \tilde{\mathbf{r}_k}(\tilde{t}) + \frac{1}{C}\left(\frac{\tau_B}{\tau_D}\delta \tilde{t}\right) \sum_{i\in\mathscr{C}_k} N_D\alpha^2 \tilde{\mathbf{r}}_{ik} + \left(\frac{\tau_B}{\tau_D}\delta\tilde{t}\right)\sum_{i=1}(\tilde{\mathbf{r}}_{ik}^2 - 1)\hat{\mathbf{r}}_{ik} + \sqrt{\frac{2}{C}}\sqrt{\frac{\tau_B}{\tau_D}\delta \tilde{t}}\tilde{\mathbf{R}}.
\end{equation}
The topological information will be updated whenever $\delta\tilde{t}$, which means when number of Brownian update reaches rational time,
\begin{equation}
R_t = \frac{\tau_D}{\tau_B},
\end{equation}
the topology will be updated.

* Topological Update
** Probability for Dissociation
Let define the detachment frequency for the chain that attached between i- and j-th micelles:
\begin{equation}
\beta_{ij} = \beta(\mathbf{r}_{ij}) \equiv \beta_0\exp\left(\frac{F(\mathbf{r}_{ij})l}{k_BT}\right),
\end{equation}
where $\beta_0$ is detachment frequency for loop chain: $\Omega\exp(E/k_BT)$.
In each $R_t$ steps for Brownian update, the topology is subject to update. Let the system has $N_{tot}$ chain ends ($N_{tot}/2$ chains). For given interval of time, $\delta t$, the expected value for number of detachment becomes 
\begin{equation}
N^\dagger = N_{tot}\bar{\beta}\delta t,
\end{equation}
where $\bar{\beta}$ is number average for the detachment frequency:
\begin{equation}
\bar{\beta} = \frac{2}{N_{tot}} \sum_{i=1}^{N_{tot}/2}\beta_i.
\end{equation}
Because of $N^\dagger \leq N_{tot}$, we have inequality
\begin{equation}
\bar{\beta}{\delta t} \leq 1.
\end{equation}
Hence, it is appropriate criterion for time increment for topological update by
\begin{equation}
\delta t < \beta_{max}^{-1},
\end{equation}
where $\beta_{max}$ is the maximum detachment frequency. Note that the $\bar{\beta}$ and $\beta_{max}$ is not clear for general case. If we have cut-off radius for association, $r_c$, however, the $\beta_{max}$ can be given by $\beta(r_c)$.

On each $\delta t$, we select random chain ends in $N_{tot}$ times. The dissociation probability for the selected chain end is given by
\begin{equation}
P^{dissoc}_k = \frac{N^\dagger}{N_{tot}}\frac{\beta_k}{\bar{\beta}} = \beta_k\delta t,
\end{equation}
# \begin{equation}
# P_k(c\to dc) = \min\left\{1, \frac{N^\dagger}{N_{tot}}\frac{\beta_k}{\bar{\beta}}\right\} = \min\left\{1, \beta_k\delta t\right\},
# \end{equation}
where $\beta_k$ is the detachment frequency for the subjected chain end. Note that probability beyond unity is automatically detached, which in principle,
\begin{equation}
P^{dissoc}_k = \min\left\{1, \beta_k \delta t\right\}.
\end{equation}

*** Non-dimensional form
Following the paper, Ianniruberto et al. (2015), the dissociation time without tension is given by
\begin{equation}
\tau_D = \beta_0^{-1} = \Omega^{-1}\exp\left(\frac{E}{k_BT}\right),
\end{equation}
which implies
\begin{equation}
\beta = \frac{1}{\tau_D}\exp(\tilde{F}\tilde{l}) \equiv \frac{1}{\tau_D}\tilde{\beta}.
\end{equation}
Therefore, we have
\begin{equation}
P^{dissoc}_k = \tilde{\beta}_k\delta \tilde{t}.
\end{equation}
The criterion for increment of dimensionless time still hold in dimensionless way:
\begin{equation}
\delta \tilde{t} < \tilde{\beta}(\tilde{r}_c)^{-1}.
\end{equation}
# with
# \begin{align}
# \beta_{ik} &= \frac{1}{\tau_D}\tilde{\beta}_{ik} \\
# \delta t &= \tau_D \delta \tilde{t}.
# \end{align}

# \begin{align}
# \tilde{\beta}_{ik} &= \tilde{\beta}_0\exp(\tilde{F}\tilde{l}),\\
# \delta \tilde{t} &= \frac{\delta t}{\tau_D},
# \end{align}
# where $\tilde{\beta}_0 = \tilde{\Omega}\exp(\tilde{E})$.


** Probability map for Association
Once the subjected chain end is detached, it immediately attach to other micelle. Let say the other chain end is attached to j-th particle, the attachment probability for a micelle is based on the Boltzmann factor:
\begin{equation}
P^{B}_{ij} = \exp\left(-\tilde{u}_{ij}\right),
\end{equation}
where index i denote possible target of micelle that originated from j-th particle. 
Let cumulative Boltzmann distribution as
\begin{equation}
F'_j(n) = \sum_{i=1}^{n}P^{B}_{ij},
\end{equation}
where $n$ is up to number of particles, $N_p$. Obviously, the $F'_j(N_p)$ is sum of all the probability that possibly connect with $j$-th particle. Then, we have normalized cumulative Boltzmann distribution:
\begin{equation}
F_j(n) = \frac{F'_j(n)}{F'_j(N_p)}.
\end{equation}
For given random number, $p\in[0, 1)$, the index function, $\mathscr{I}$, is defined 
\begin{equation}
\mathscr{I}(p) = \left\{\begin{array}{cc} 1 & \textrm{if }  p < F_j(1) \\
2 & \textrm{if } F_j(1) \leq p < F_j(2) \\
\vdots & \vdots \\
N_p & \textrm{if } F_j(N_p - 1) \leq p.
\end{array}\right.
\end{equation}
Therefore, for given random number, $p$, the index of target micelle is given by $\mathscr{I}(p)$. For performance, the cumulating order will be changed through the sorting based on the probability. In addition, the cut-off scheme will be implemented through cell-list method, which is not described on here.

* Summary
In non-dimensional space, the Brownian update is based on the $\frac{\tau_B}{\tau_D}\delta\tilde{t}$ while the topological update is based $\delta \tilde{t}$. It means we have $R_t$ numbers to update Brownian motion, then to update one instant time for association topology. The /Brownian update/ is based on simplified Euler integrator described in the time evolution equation for micelle positions. The /topological update/ follows following steps:\\
(1) selecting chain ends based on the uniform random number;\\
(2) for given selected chain, generate random uniform number between 0 and 1, and check the dissociation probability;\\
(3) if the chain is detached, generate random uniform number between 0 and 1, and selecting target micelle to attach based on index function;\\
(4) go to the first step until iteration number reaches $N_{tot}$ times.



# ** Time Scales
# Recall the ratio of time scales between Brownian and topological updates, $R_t$, the $\delta t$ in the dissociation probability 


# \begin{equation}
# P'(
# \end{equation}



# Since the system characteristic time is given by dissociation time, $\tau_D(>\tau_B)$, we can re-map the given non-dimenional form into the characteristic time
# \begin{equation}
# \tilde{\mathbf{r}}_k(\tilde{t} + \delta \tilde{t}) = \tilde{\mathbf{r}}_k(\tilde{t}) + \frac{1}{C}\delta\tilde{t}\sum_{i\in\mathscr{C}_k} \frac{N_D}{2}\alpha\tilde{\mathbf{r}}_{ik} + \delta\tilde{t}  \sum_{i=1, i\neq k}^{N_p} (\tilde{r}_{ik}^2 - 1)\hat{\mathbf{r}_{ik}} + \sqrt{\frac{2}{C}}\sqrt{\delta \tilde{t}}\tilde{\mathbf{R}},
# \end{equation}



# The system characteristic time is given by dissociation time, $\tau_D$ with $\tau_D > \tau_B$. The evolution equation can be expressed by
# \begin{equation}
# \tilde{\mathbf{r}}_k(\tilde{t} + \delta \tilde{t}) = \tilde{\mathbf{r}}_k(\tilde{t}) + \frac{\tau_D}{\tau_C C}\delta\tilde{t}\sum_{i\in\mathscr{C}_k} \frac{N_D}{2}\alpha\tilde{\mathbf{r}}_{ik} + \frac{\tau_D}{\tau_C}\delta\tilde{t}  \sum_{i=1, i\neq k}^{N_p} (\tilde{r}_{ik}^2 - 1)\hat{\mathbf{r}_{ik}} + \sqrt{\frac{\tau_D}{\tau_C}}\sqrt{\delta \tilde{t}}\tilde{\mathbf{r}},
# \end{equation}


# Let characteristic time as dissociation time, $\tau_D$ with $\tau_D > \tau_B$, the Brownian update is based on
# , the given non-dimensional form for the evolution equation becomes
# \begin{equation}
# \tilde{\mathbf{r}}_k(\tilde{t} + \delta \tilde{t}) = \tilde{\mathbf{r}}_k(\tilde{t}) + \frac{k_BT\tau_D}{R_0^2\zeta}\delta\tilde{t}\sum_{i\in\mathscr{C}_k} \frac{N_D}{2}\alpha\tilde{\mathbf{r}}_{ik} + \frac{k_BTC\tau_D}{R_0^2 \zeta}\delta\tilde{t}  \sum_{i=1, i\neq k}^{N_p} (\tilde{r}_{ik}^2 - 1)\hat{\mathbf{r}_{ik}} + \sqrt{\frac{2k_BT\tau_D}{R_0^2\zeta}}\sqrt{\delta \tilde{t}}\tilde{\mathbf{r}},
# \end{equation}

# If we define Brownian time step, $\tau_B$:
# \begin{equation}
# \tau_B = \frac{R_0^2\zeta}{k_BT C},
# \end{equation}
# the $\tau_B$ is much shorter than the $\tau_D$, and the ratio is arbitrary value at this moment. On this regards, we can express the evolution equation based on Brownian time update


# Let $\tau_D$ be dissociation time and $\tau_B$ is Brownian update time scale which is given by
# \begin{equation}
# \tau_B = \frac{R_0^2\zeta}{k_BT C},
# \end{equation}
# the time step to update should be based on $\tau_B$. Let characteristic time step as $\tau_

# Because of $\tau_D > \tau_B$, the dimenionless time step for Brownian motion follows that time step:
# \begin{equation}
# \delta\tilde{t}_B = \frac{\delta\tilde{t}}{\tau_D/\tau_B} = \frac{\tau_B\delta\tilde{t}}{\tau_D}.
# \end{equation}
# In this case, the increment time step becomes
# \begin{equation}
# \delta t = \tau_D \delta \tilde_{t}
# \end{equation}

# where $\alpha = R_0/R_c$. For simplification, let integrator time scale:
# \begin{equation}
# \tau_I = \frac{R_0^2\zeta}{k_BT C},
# \end{equation}
# we have
# \begin{equation}
# \tilde{\mathbf{r}}_k(\tilde{t} + \delta \tilde{t}) = \tilde{\mathbf{r}}_k(\tilde{t}) + \frac{\tau_D}{\tau_C C}\delta\tilde{t}\sum_{i\in\mathscr{C}_k} \frac{N_D}{2}\alpha\tilde{\mathbf{r}}_{ik} + \frac{\tau_D}{\tau_C}\delta\tilde{t}  \sum_{i=1, i\neq k}^{N_p} (\tilde{r}_{ik}^2 - 1)\hat{\mathbf{r}_{ik}} + \sqrt{\frac{\tau_D}{\tau_C}}\sqrt{\delta \tilde{t}}\tilde{\mathbf{r}},
# \end{equation}

# The characteristic length is given by micelle dimension, $R_0$, and the time scale for the 


# The Euler integrator for the given evolution equation is given by
# \begin{equation}
# \mathbf{r}_k(t+\delta t) = 
# \end{equation}

# the characteristic length scale for the system is given by micelle dimension, $R_0$, and the time scale is dissociation time, $\tau_D$. 

# Let $\tau_B$ be the Brownian time steps and $\tau_D$ be dissociation time step:
# \begin{equation}
# \tau_B = \frac{\zeta R_0^2}{k_BT C},
# \end{equation}
# where $\zeta$ is friction coefficient for micelle, R_0 is micelle dimension which is characteristic length for the system, and $C$ is repulsive coefficient.
# Consider the 


# The given evolution equation for the previous set is described on
# \begin{equation}
# \frac{\partial \mathbf{r}_k}{\partial t} = \frac{1}{\zeta}\left(\sum_{i\in\mathscr{C}_k} \mathbf{F}^{(c)}(\mathbf{r}_i, \mathbf{r}_k) + \sum_i \mathbf{F}^{(r)}(\mathbf{r}_i, \mathbf{r}_k) + \mathbf{F}^{(s)}(\mathbf{r}_k)\right),
# \end{equation}
# where the information for $\mathscr{C}_k$ for all k in $[0, N_p]$ is already measured during stochastic steps.

# In this case, we can think that the time is passing during Brownian update while the stochastic step can be regarded infinite for each Brownian update.

# Since the equation evolve Brownian time, we can choose the characteristic time step as
# \begin{equation}
# t_c = \frac{\zeta}{k_BT}R_0^2,
# \end{equation}
# where $R_0$ is micell dimension with the characteristic length:
# \begin{equation}
# r_c = R_0.
# \end{equation}

# \begin{equation}
# \tilde{\mathbf{r}}_k(\tilde{t} + \delta \tilde{t}) = \tilde{\mathbf{r}}_k(\tilde{t}) + \sum_{i\in\mathscr{C}_k}\tilde{\mathbf{F}}^{(c)}(\tilde{\mathbf{r}}_i, \tilde{\mathbf{r}}_k) + \sum_{i}\tilde{\mathbf{F}}^{(r)}(\tilde{\mathbf{r}}_i, \tilde{\mathbf{r}}_k)\delta \tilde{t} + \tilde{\mathbf{F}}^{(s)}_k\sqrt{\delta\tilde{t}},
# \end{equation}

# \begin{align}
# \tilde{\mathbf{F}}^{(r)}(\tilde{\mathbf{r}}_i, \tilde{\mathbf{r}}_j) &= -\left(1-\tilde{\mathbf{r}}_{ij}^2\right)\frac{\tilde{\mathbf{r}}_{ij}}{\tilde{r}_{ij}}\\
# \tilde{\mathbf{F}}^{(s)} &= \sqrt{\frac{2}{3}}\tilde{\mathbf{R}}
# \end{align}

# \begin{align}
#   \tilde{U}^{(c)}(\tilde{\mathbf{r}}_{ij}) &= \frac{N_D}{2}\tilde{\mathbf{r}}_{ij}^2,\\
#   \tilde{\mathbf{F}}^{(c)}(\tilde{\mathbf{r}}_{ij}) &= N_D\tilde{\mathbf{r}}_{ij}.
# \end{align}

# \begin{equation}
# w(\delta t, \tau) = 1 - \exp\left(-\frac{\delta t}{\tau}\right)
# \end{equation}

# \begin{equation}
# P_{ik} = \frac{\exp(-\tilde{u}_{ik})}{\sum_{j}\exp(-\tilde{u}_{jk})}
# \end{equation}





# * Modification
# If it is not the case, 
