
#+TITLE:Probability Density for Association Map
#+AUTHOR: Gun Woo Park

* Schematic Sketch of Association Map
For given elastic potential of a chain, $U(r)$, the attachment probability follows Boltzmann map as continuous manner:
\begin{equation}
P^\prime(r)= \exp\left(-\frac{U(r)}{k_BT}\right),
\end{equation}
where $r$ denote the length of stretched chain.
In this manner, the normalized probability is given by
\begin{equation}
P(r) = \frac{P^\prime(r)}{\int P^\prime(r) dr}
\end{equation}
Note that the probability density is given by
\begin{equation}
P(r)dr = \frac{P^\prime(r) dr}{\int P^\prime(r) dr}
\end{equation}

* The previous approach

In order to descritize (quantization), the cumulative Boltzmann distribution is defined as follow
\begin{equation}
F_j^\prime (n) := \sum_{i=1}^{n}P(r_{ij}),
\label{eq:basic_cumulation}
\end{equation}
where $n$ is number of particles subject to cumulation and $n\leq N_p$, and $i$ and $j$ are indice for micelle. From this point of view, the normalized cumulative Boltzmann distribution is given by
\begin{equation}
F_j(n) = \frac{F_j^\prime(n)}{F_j^\prime(N_p)}.
\end{equation}
Now, we can define index function which determine index for micelle, $i$, subject to associate with the micelle $j$. For the given rando number, $\mathbf{p}\in [0, 1)$, the index function, $\mathscr{I}$, is given by
\begin{equation}
\mathscr{I}(p) = \left\{\begin{array}{cc} 1 & \textrm{if }  p < F_j(1) \\
2 & \textrm{if } F_j(1) \leq p < F_j(2) \\
\vdots & \vdots \\
N_p & \textrm{if } F_j(N_p - 1) \leq p.
\end{array}\right.
\end{equation}


* Interpretation of Quantization for Continuous Probability Distribution Function
It comes to my concerns that the descritization version for equation \eqref{eq:basic_cumulation} was wrong since the given probability distribution is continuous. The given cumulation scheme is only valid for probability mass function where the probability is given by discrete manner. 

Without consider of discretization, the cumulative distribution function of X with the density $f_X$ becomes
\begin{equation}
F_X(x) = \int_{-\infty}^{x}f_X(u)du,
\end{equation}
with the formal definition of density $f_X$ if $f_X$ is continuous at $x$:
\begin{equation}
f_X(x) = \frac{d}{dx}F_{X}(x).
\end{equation}
Therefore, the formal definition of finding probability between $a$ and $b$ becomes
\begin{equation}
Pr[a\leq X\leq b] = \int_{a}^{b} f_{X}(x)dx.
\end{equation}
Discretization of the finding probability is simply becomes
\begin{equation}
Pr(x < X < x + dx) = f(x)dx.
\end{equation}

In conclusion, the cumulative Boltzmann distribution should be
\begin{equation}
F_j^\prime (n) := \sum_{i=1}^{n} P(r_{ij})dr(n),
\end{equation}
where the index is already sorted by increasing order with respect to $n$ and 
\begin{equation}
dr(n) = r_{n, j} - r_{n-1, j}.
\end{equation}
