
#+TITLE:Probability Density for Association Map
#+AUTHOR: Gun Woo Park

* Schematic Sketch of Association Map
For given elastic potential of a chain, $U(r)$, the attachment probability follows Boltzmann map as continuous manner:
\begin{equation}
P^\prime(r)= \exp\left(-\frac{U(r)}{k_BT}\right),
\end{equation}
where $r$ denote the length of stretched chain.
In this manner, the normalized probability is given by
\begin{equation}
P(r) = \frac{P^\prime(r)}{\int P^\prime(r) dr}
\end{equation}
Note that the probability density is given by
\begin{equation}
P(r)dr = \frac{P^\prime(r) dr}{\int P^\prime(r) dr}
\end{equation}

* The previous approach

In order to descritize (quantization), the cumulative Boltzmann distribution is defined as follow
\begin{equation}
F_j^\prime (n) := \sum_{i=1}^{n}P(r_{ij}),
\label{eq:basic_cumulation}
\end{equation}
where $n$ is number of particles subject to cumulation and $n\leq N_p$, and $i$ and $j$ are indice for micelle. From this point of view, the normalized cumulative Boltzmann distribution is given by
\begin{equation}
F_j(n) = \frac{F_j^\prime(n)}{F_j^\prime(N_p)}.
\end{equation}
Now, we can define index function which determine index for micelle, $i$, subject to associate with the micelle $j$. For the given rando number, $\mathbf{p}\in [0, 1)$, the index function, $\mathscr{I}$, is given by
\begin{equation}
\mathscr{I}(p) = \left\{\begin{array}{cc} 1 & \textrm{if }  p < F_j(1) \\
2 & \textrm{if } F_j(1) \leq p < F_j(2) \\
\vdots & \vdots \\
N_p & \textrm{if } F_j(N_p - 1) \leq p.
\end{array}\right.
\end{equation}


* Interpretation of Quantization for Continuous Probability Distribution Function
It comes to my concerns that the descritization version for equation \eqref{eq:basic_cumulation} was wrong since the given probability distribution is continuous. The given cumulation scheme is only valid for probability mass function where the probability is given by discrete manner. 

Without consider of discretization, the cumulative distribution function of X with the density $f_X$ becomes
\begin{equation}
F_X(x) = \int_{-\infty}^{x}f_X(u)du,
\end{equation}
with the formal definition of density $f_X$ if $f_X$ is continuous at $x$:
\begin{equation}
f_X(x) = \frac{d}{dx}F_{X}(x).
\end{equation}
Therefore, the formal definition of finding probability between $a$ and $b$ becomes
\begin{equation}
Pr[a\leq X\leq b] = \int_{a}^{b} f_{X}(x)dx.
\end{equation}

With this sense, the cumulative Boltzmann distribution discretized by sorted distance map from the subjected micelle:
\begin{equation}
F_j^\prime (n) := \int_0^{r_{nj}} P^\prime (r) dr.
\end{equation}
Note again that the distance map is already sorted in increasing order with respect to index $n$.
For Gaussian chain, it is obvious that the form for cumulative distribution has error function form, which can be implemented by many mathematical library and faster than numerical integration.


* Approximation
One of the most crude approximation can be uniform up to next finding distance:
\begin{equation}
F_j^\prime (n) := \sum_{i=1}^{n} P(r_{ij})dr(n),
\end{equation}
where
\begin{equation}
dr(n) = r_{n, j} - r_{n-1, j}.
\end{equation}
Note that it overestimate the probability in the first range due to the sparseness. 
With simple revision, crude first-order approximation can be used as
\begin{equation}
F_j^\prime (n) := \sum_{i=1}^{n-1} \frac{1}{2}\left(P(r_{ij}) + P(r_{(i+1)j}))dr(n),
\end{equation}
with the trapezoidal rule. 






# # Therefore, it is quite nature that we can descritization the given probability when $dx$ is small enough:
# # \begin{equation}
# # Pr(x < X < x + dx) = f(x)dx.
# # \end{equation}

# # It is of importance to apply the continuous case into our simulation since the micelle has repulsive potential. Let assume that the second suggestion of pair of micelle has the distance $0.5 R_0$ (the first is itself, $r=0$) because the suggestion probability in this range is very small. 
# # For this reason, the second probability cannot be descritized as previous one, but 
# # \begin{equation}
# # Pr(0 < r < 0.5R_0) = \frac{1}{Z}\int_{0}^{0.5 R_0} \exp\left(F(r)l_c/k_BT\right) dr,
# # \end{equation}
# # while the pair that range higher than $R_0$ appropriately given by
# # \begin{equation}
# # Pr(r_k < r < r_{k+1}) = \exp\left(F(r)l_c/k_BT\right) dr_k \quad\textrm{ with }dr_k = r_{k+1} - r_{k}
# # \end{equation}

# # The suggestion probability in the $r < 0.5 R_0$ is too small in consequence the probability is not really described by
# # \begin{equation}
# # Pr(0 < R < 0.5 
# # \end{equation}


# In conclusion, the cumulative Boltzmann distribution should be
# \begin{equation}
# F_j^\prime (n) := \sum_{i=1}^{n} P(r_{ij})dr(n),
# \end{equation}
# where the index is already sorted by increasing order with respect to $n$ and 
# \begin{equation}
# dr(n) = r_{n, j} - r_{n-1, j}.
# \end{equation}
